In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("India_Ecommerce_Unclean_Dataset.csv")

In [3]:
df

,Order_ID,Order_Date,Delivery_Date,Customer_Name,Customer_Email,Customer_Phone,Customer_City,Customer_State,Customer_Pincode,Region,...,Unit_Price_INR,Discount_Percent,Tax_Percent,Gross_Amount_INR,Net_Amount_INR,Payment_Method,Payment_Status,Shipping_Method,Customer_Rating,Return_Status
0,ORD00000001,28/09/2023,07/10/2023,Rohan Agarwal,rohan.agarwal769@yahoo.co.in,9.186701e+11,Chenai,KA,684090.0,NaN,...,119742.81,26.31,5.0,119742.81,92650.40,cash,NaN,Next Day,4.4,N
1,ORD00000002,2023-12-11,2023-12-12,suresh Kumar,suresh.kumar998yahoo.co.in,9.193598e+11,PUNE,Maharashtra,186238.0,East India,...,140712.99,4.39,12.0,984990.93,1054759.81,NaN,Pending,Next Day,4.5,1
2,ORD00000003,2021-10-24,2021-11-04,Sunita Nair,sunita.nair877@yahoo.co.in,9.173318e+11,Indore,Bihar,3803.0,north,...,15846.47,9.26,12.0,63385.88,64418.31,Debit Card,pending,Standard,1.2,NaN
3,ORD00000004,2024-03-31,2024-04-06,Pooja Das,pooja.das184gmail.com,9.171830e+11,Kolkata,Andhra Pradesh,739883.0,SOUTH,...,132045.51,17.80,0.0,1591319.56,1308064.68,Debit Card,Paid,Same Day,4.0,Yes
4,ORD00000005,07-01-2022,07-11-2022,Kavya Sen,kavya.sen379@hotmail.com,9.189122e+11,Ahemadabad,NaN,5454.0,NaN,...,66250.95,45.25,28.0,287771.80,201670.48,upi,NaN,Economy,2.2,No Return
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,ORD00099996,NaN,NaN,Pooja Chopra,pooja.chopra868@gmail.com,9.180279e+11,Mumbai,TN,792197.0,SOUTH,...,32914.31,56.74,18.0,65828.62,33603.40,DEBIT CARD,Paid,standard,1.0,No Return
99996,ORD00036659,2022-05-21,2022-05-27,meena Rao,meena.rao409@hotmail.com,9.168083e+11,PUNE,NaN,614404.0,North,...,57356.55,31.30,5.0,401495.85,289619.03,Cash on Delivery,PAID,Standard,1.4,Yes
99997,ORD00099998,03-Oct-2023,14-Oct-2023,Rahul Patel,rahul.patel827@rediffmail.com,9.195276e+11,NaN,Bihar,250996.0,SOUTH,...,119512.97,22.06,12.0,1075616.73,938935.96,Credit Card,PAID,NaN,1.9,No Return
99998,ORD00099999,2023-10-25,2023-11-05,POOJA Gupta,pooja.gupta101@hotmail.com,9.171351e+11,DELHI,Kerala,990079.0,north,...,34764.23,21.12,18.0,34764.23,32357.99,NaN,Failed,Next Day,4.9,No Return
99999,ORD00100000,01-25-2024,02-06-2024,Kavya Reddy,kavya.reddy225@outlook.com,9.190548e+11,PUNE,Maharashtra,343131.0,Northeast,...,119670.92,57.04,0.0,718025.52,308463.76,DEBIT CARD,PAID,Express,4.2,1

In [5]:
df.head()

,Order_ID,Order_Date,Delivery_Date,Customer_Name,Customer_Email,Customer_Phone,Customer_City,Customer_State,Customer_Pincode,Region,...,Unit_Price_INR,Discount_Percent,Tax_Percent,Gross_Amount_INR,Net_Amount_INR,Payment_Method,Payment_Status,Shipping_Method,Customer_Rating,Return_Status
0,ORD00000001,28/09/2023,07/10/2023,Rohan Agarwal,rohan.agarwal769@yahoo.co.in,9.186701e+11,Chenai,KA,684090.0,NaN,...,119742.81,26.31,5.0,119742.81,92650.40,cash,NaN,Next Day,4.4,N
1,ORD00000002,2023-12-11,2023-12-12,suresh Kumar,suresh.kumar998yahoo.co.in,9.193598e+11,PUNE,Maharashtra,186238.0,East India,...,140712.99,4.39,12.0,984990.93,1054759.81,NaN,Pending,Next Day,4.5,1
2,ORD00000003,2021-10-24,2021-11-04,Sunita Nair,sunita.nair877@yahoo.co.in,9.173318e+11,Indore,Bihar,3803.0,north,...,15846.47,9.26,12.0,63385.88,64418.31,Debit Card,pending,Standard,1.2,NaN
3,ORD00000004,2024-03-31,2024-04-06,Pooja Das,pooja.das184gmail.com,9.171830e+11,Kolkata,Andhra Pradesh,739883.0,SOUTH,...,132045.51,17.80,0.0,1591319.56,1308064.68,Debit Card,Paid,Same Day,4.0,Yes
4,ORD00000005,07-01-2022,07-11-2022,Kavya Sen,kavya.sen379@hotmail.com,9.189122e+11,Ahemadabad,NaN,5454.0,NaN,...,66250.95,45.25,28.0,287771.80,201670.48,upi,NaN,Economy,2.2,No Return

In [6]:
df.tail()

,Order_ID,Order_Date,Delivery_Date,Customer_Name,Customer_Email,Customer_Phone,Customer_City,Customer_State,Customer_Pincode,Region,...,Unit_Price_INR,Discount_Percent,Tax_Percent,Gross_Amount_INR,Net_Amount_INR,Payment_Method,Payment_Status,Shipping_Method,Customer_Rating,Return_Status
99995,ORD00099996,NaN,NaN,Pooja Chopra,pooja.chopra868@gmail.com,9.180279e+11,Mumbai,TN,792197.0,SOUTH,...,32914.31,56.74,18.0,65828.62,33603.40,DEBIT CARD,Paid,standard,1.0,No Return
99996,ORD00036659,2022-05-21,2022-05-27,meena Rao,meena.rao409@hotmail.com,9.168083e+11,PUNE,NaN,614404.0,North,...,57356.55,31.30,5.0,401495.85,289619.03,Cash on Delivery,PAID,Standard,1.4,Yes
99997,ORD00099998,03-Oct-2023,14-Oct-2023,Rahul Patel,rahul.patel827@rediffmail.com,9.195276e+11,NaN,Bihar,250996.0,SOUTH,...,119512.97,22.06,12.0,1075616.73,938935.96,Credit Card,PAID,NaN,1.9,No Return
99998,ORD00099999,2023-10-25,2023-11-05,POOJA Gupta,pooja.gupta101@hotmail.com,9.171351e+11,DELHI,Kerala,990079.0,north,...,34764.23,21.12,18.0,34764.23,32357.99,NaN,Failed,Next Day,4.9,No Return
99999,ORD00100000,01-25-2024,02-06-2024,Kavya Reddy,kavya.reddy225@outlook.com,9.190548e+11,PUNE,Maharashtra,343131.0,Northeast,...,119670.92,57.04,0.0,718025.52,308463.76,DEBIT CARD,PAID,Express,4.2,1

In [8]:
df.columns

Index(['Order_ID', 'Order_Date', 'Delivery_Date', 'Customer_Name',
       'Customer_Email', 'Customer_Phone', 'Customer_City', 'Customer_State',
       'Customer_Pincode', 'Region', 'Category', 'Sub_Category',
       'Product_Name', 'Product_SKU', 'Quantity', 'Unit_Price_INR',
       'Discount_Percent', 'Tax_Percent', 'Gross_Amount_INR', 'Net_Amount_INR',
       'Payment_Method', 'Payment_Status', 'Shipping_Method',
       'Customer_Rating', 'Return_Status'],
      dtype='object')

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 25 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Order_ID          99500 non-null   object
 1   Order_Date        98990 non-null   object
 2   Delivery_Date     97031 non-null   object
 3   Customer_Name     99014 non-null   object
 4   Customer_Email    99018 non-null   object
 5   Customer_Phone    98996 non-null   float64
 6   Customer_City     93215 non-null   object
 7   Customer_State    88108 non-null   object
 8   Customer_Pincode  99035 non-null   float64
 9   Region            81744 non-null   object
 10  Category          93659 non-null   object
 11  Sub_Category      98995 non-null   object
 12  Product_Name      97992 non-null   object
 13  Product_SKU       100000 non-null  object
 14  Quantity          100000 non-null  int64
 15  Unit_Price_INR    99500 non-null   object
 16  Discount_Percent  98926 non-null   float64
 17  Tax_Percent       98027 non-null   float64
 18  Gross_Amount_INR  100000 non-null  float64
 19  Net_Amount_INR    97045 non-null   float64
 20  Payment_Method    86780 non-null   object
 21  Payment_Status    82047 non-null   object
 22  Shipping_Method   77579 non-null   object
 23  Customer_Rating   98006 non-null   float64
 24  Return_Status     90628 non-null   object
dtypes: float64(7), int64(1), object(17)
memory usage: 19.1+ MB

In [11]:
df.shape

(100000, 25)

In [12]:
df.isnull().sum()

Order_ID              500
Order_Date           1010
Delivery_Date        2969
Customer_Name         986
Customer_Email        982
Customer_Phone       1004
Customer_City        6785
Customer_State      11892
Customer_Pincode      965
Region              18256
Category             6341
Sub_Category         1005
Product_Name         2008
Product_SKU             0
Quantity                0
Unit_Price_INR        500
Discount_Percent     1074
Tax_Percent          1973
Gross_Amount_INR        0
Net_Amount_INR       2955
Payment_Method      13220
Payment_Status      17953
Shipping_Method     22421
Customer_Rating      1994
Return_Status        9372
dtype: int64

In [13]:
df.describe()

,Customer_Phone,Customer_Pincode,Quantity,Discount_Percent,Tax_Percent,Gross_Amount_INR,Net_Amount_INR,Customer_Rating
count,9.899600e+04,99035.000000,100000.000000,98926.000000,98027.000000,1.000000e+05,9.704500e+04,98006.000000
mean,8.993317e+11,527900.944262,6.189760,31.663346,12.631714,4.794456e+05,3.718308e+05,3.035506
std,1.295726e+11,277762.101224,22.116066,25.363916,9.839965,1.941093e+06,1.608757e+06,1.488470
min,1.030000e+02,103.000000,-9.000000,-196.870000,0.000000,0.000000e+00,-1.824893e+07,-10.000000
25%,9.169359e+11,297091.500000,3.000000,14.720000,5.000000,1.182421e+05,8.275352e+04,2.000000
50%,9.179565e+11,532496.000000,5.000000,30.250000,12.000000,2.863406e+05,2.113656e+05,3.000000
75%,9.189785e+11,766195.000000,7.000000,45.790000,18.000000,5.661988e+05,4.317752e+05,4.000000
max,9.200000e+11,999993.000000,499.000000,199.850000,28.000000,7.307701e+07,9.353857e+07,10.000000