In [3]:
import numpy as np
import pandas as pd
import matplotlib as plt
import seaborn as sns

In [4]:
df = pd.read_csv("India_Ecommerce_Unclean_Dataset.csv")

In [5]:
df

,Order_ID,Order_Date,Delivery_Date,Customer_Name,Customer_Email,Customer_Phone,Customer_City,Customer_State,Customer_Pincode,Region,...,Unit_Price_INR,Discount_Percent,Tax_Percent,Gross_Amount_INR,Net_Amount_INR,Payment_Method,Payment_Status,Shipping_Method,Customer_Rating,Return_Status
0,ORD00000001,28-09-2023,07-10-2023,Rohan Agarwal,rohan.agarwal769@yahoo.co.in,9.186700e+11,Chenai,KA,684090.0,NaN,...,119742.81,26.31,5.0,119742.81,92650.40,cash,NaN,Next Day,4.4,N
1,ORD00000002,11-12-2023,12-12-2023,suresh Kumar,suresh.kumar998yahoo.co.in,9.193600e+11,PUNE,Maharashtra,186238.0,East India,...,140712.99,4.39,12.0,984990.93,1054759.81,NaN,Pending,Next Day,4.5,1
2,ORD00000003,24-10-2021,04-11-2021,Sunita Nair,sunita.nair877@yahoo.co.in,9.173320e+11,Indore,Bihar,3803.0,north,...,15846.47,9.26,12.0,63385.88,64418.31,Debit Card,pending,Standard,1.2,NaN
3,ORD00000004,31-03-2024,06-04-2024,Pooja Das,pooja.das184gmail.com,9.171830e+11,Kolkata,Andhra Pradesh,739883.0,SOUTH,...,132045.51,17.80,0.0,1591319.56,1308064.68,Debit Card,Paid,Same Day,4.0,Yes
4,ORD00000005,07-01-2022,07-11-2022,Kavya Sen,kavya.sen379@hotmail.com,9.189120e+11,Ahemadabad,NaN,5454.0,NaN,...,66250.95,45.25,28.0,287771.80,201670.48,upi,NaN,Economy,2.2,No Return
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,ORD00099996,NaN,NaN,Pooja Chopra,pooja.chopra868@gmail.com,9.180280e+11,Mumbai,TN,792197.0,SOUTH,...,32914.31,56.74,18.0,65828.62,33603.40,DEBIT CARD,Paid,standard,1.0,No Return
99996,ORD00036659,21-05-2022,27-05-2022,meena Rao,meena.rao409@hotmail.com,9.168080e+11,PUNE,NaN,614404.0,North,...,57356.55,31.30,5.0,401495.85,289619.03,Cash on Delivery,PAID,Standard,1.4,Yes
99997,ORD00099998,03-Oct-23,14-Oct-23,Rahul Patel,rahul.patel827@rediffmail.com,9.195280e+11,NaN,Bihar,250996.0,SOUTH,...,119512.97,22.06,12.0,1075616.73,938935.96,Credit Card,PAID,NaN,1.9,No Return
99998,ORD00099999,25-10-2023,05-11-2023,POOJA Gupta,pooja.gupta101@hotmail.com,9.171350e+11,DELHI,Kerala,990079.0,north,...,34764.23,21.12,18.0,34764.23,32357.99,NaN,Failed,Next Day,4.9,No Return
99999,ORD00100000,01-25-2024,02-06-2024,Kavya Reddy,kavya.reddy225@outlook.com,9.190550e+11,PUNE,Maharashtra,343131.0,Northeast,...,119670.92,57.04,0.0,718025.52,308463.76,DEBIT CARD,PAID,Express,4.2,1

## Data Overview

In [6]:
df.head(6)

,Order_ID,Order_Date,Delivery_Date,Customer_Name,Customer_Email,Customer_Phone,Customer_City,Customer_State,Customer_Pincode,Region,...,Unit_Price_INR,Discount_Percent,Tax_Percent,Gross_Amount_INR,Net_Amount_INR,Payment_Method,Payment_Status,Shipping_Method,Customer_Rating,Return_Status
0,ORD00000001,28-09-2023,07-10-2023,Rohan Agarwal,rohan.agarwal769@yahoo.co.in,9.186700e+11,Chenai,KA,684090.0,NaN,...,119742.81,26.31,5.0,119742.81,92650.40,cash,NaN,Next Day,4.4,N
1,ORD00000002,11-12-2023,12-12-2023,suresh Kumar,suresh.kumar998yahoo.co.in,9.193600e+11,PUNE,Maharashtra,186238.0,East India,...,140712.99,4.39,12.0,984990.93,1054759.81,NaN,Pending,Next Day,4.5,1
2,ORD00000003,24-10-2021,04-11-2021,Sunita Nair,sunita.nair877@yahoo.co.in,9.173320e+11,Indore,Bihar,3803.0,north,...,15846.47,9.26,12.0,63385.88,64418.31,Debit Card,pending,Standard,1.2,NaN
3,ORD00000004,31-03-2024,06-04-2024,Pooja Das,pooja.das184gmail.com,9.171830e+11,Kolkata,Andhra Pradesh,739883.0,SOUTH,...,132045.51,17.80,0.0,1591319.56,1308064.68,Debit Card,Paid,Same Day,4.0,Yes
4,ORD00000005,07-01-2022,07-11-2022,Kavya Sen,kavya.sen379@hotmail.com,9.189120e+11,Ahemadabad,NaN,5454.0,NaN,...,66250.95,45.25,28.0,287771.80,201670.48,upi,NaN,Economy,2.2,No Return
5,ORD00000006,08-09-2021,18-09-2021,Sanjay Joshi,sanjay.joshi235@gmail.com,9.199390e+11,DELHI,Rajasthan,115208.0,SOUTH,...,129473.12,44.04,28.0,129473.12,92740.04,upi,paid,Standard,4.1,Yes

In [7]:
df.tail()

,Order_ID,Order_Date,Delivery_Date,Customer_Name,Customer_Email,Customer_Phone,Customer_City,Customer_State,Customer_Pincode,Region,...,Unit_Price_INR,Discount_Percent,Tax_Percent,Gross_Amount_INR,Net_Amount_INR,Payment_Method,Payment_Status,Shipping_Method,Customer_Rating,Return_Status
99995,ORD00099996,NaN,NaN,Pooja Chopra,pooja.chopra868@gmail.com,9.180280e+11,Mumbai,TN,792197.0,SOUTH,...,32914.31,56.74,18.0,65828.62,33603.40,DEBIT CARD,Paid,standard,1.0,No Return
99996,ORD00036659,21-05-2022,27-05-2022,meena Rao,meena.rao409@hotmail.com,9.168080e+11,PUNE,NaN,614404.0,North,...,57356.55,31.30,5.0,401495.85,289619.03,Cash on Delivery,PAID,Standard,1.4,Yes
99997,ORD00099998,03-Oct-23,14-Oct-23,Rahul Patel,rahul.patel827@rediffmail.com,9.195280e+11,NaN,Bihar,250996.0,SOUTH,...,119512.97,22.06,12.0,1075616.73,938935.96,Credit Card,PAID,NaN,1.9,No Return
99998,ORD00099999,25-10-2023,05-11-2023,POOJA Gupta,pooja.gupta101@hotmail.com,9.171350e+11,DELHI,Kerala,990079.0,north,...,34764.23,21.12,18.0,34764.23,32357.99,NaN,Failed,Next Day,4.9,No Return
99999,ORD00100000,01-25-2024,02-06-2024,Kavya Reddy,kavya.reddy225@outlook.com,9.190550e+11,PUNE,Maharashtra,343131.0,Northeast,...,119670.92,57.04,0.0,718025.52,308463.76,DEBIT CARD,PAID,Express,4.2,1

In [8]:
df.sample(3)

,Order_ID,Order_Date,Delivery_Date,Customer_Name,Customer_Email,Customer_Phone,Customer_City,Customer_State,Customer_Pincode,Region,...,Unit_Price_INR,Discount_Percent,Tax_Percent,Gross_Amount_INR,Net_Amount_INR,Payment_Method,Payment_Status,Shipping_Method,Customer_Rating,Return_Status
92913,ORD00092914,03-03-2021,10-03-2021,Lakshmi Iyer,lakshmi.iyer361yahoo.co.in,9.188980e+11,Bhopal,Telangana,155830.0,NaN,...,105413.34,12.44,0.0,316240.02,276899.76,Cash on Delivery,pending,Same Day,2.2,NaN
95867,ORD00095868,19-11-2022,03-12-2022,Kavya Mehta,kavya.mehta349@hotmail.com,9.170490e+11,Kolkata,Maharashtra,217381.0,NaN,...,INR 59207.71,39.10,28.0,296038.55,230767.97,Debit Card,FAILED,NaN,3.2,1
23091,ORD00023092,24-09-2020,NaN,Pooja Patel,pooja.patel254@hotmail.com,9.160980e+11,Surat,Madhya Pradesh,468481.0,NaN,...,81430.21,12.69,18.0,325720.84,335576.50,NaN,NaN,Economy,4.1,No Return

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 25 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Order_ID          99500 non-null   object
 1   Order_Date        98990 non-null   object
 2   Delivery_Date     97031 non-null   object
 3   Customer_Name     99014 non-null   object
 4   Customer_Email    99018 non-null   object
 5   Customer_Phone    98996 non-null   float64
 6   Customer_City     93215 non-null   object
 7   Customer_State    88108 non-null   object
 8   Customer_Pincode  99035 non-null   float64
 9   Region            81744 non-null   object
 10  Category          93659 non-null   object
 11  Sub_Category      98995 non-null   object
 12  Product_Name      97992 non-null   object
 13  Product_SKU       100000 non-null  object
 14  Quantity          100000 non-null  int64
 15  Unit_Price_INR    99500 non-null   object
 16  Discount_Percent  98926 non-null   float64
 17  Tax_Percent       98027 non-null   float64
 18  Gross_Amount_INR  100000 non-null  float64
 19  Net_Amount_INR    97045 non-null   float64
 20  Payment_Method    86780 non-null   object
 21  Payment_Status    82047 non-null   object
 22  Shipping_Method   77579 non-null   object
 23  Customer_Rating   98006 non-null   float64
 24  Return_Status     90628 non-null   object
dtypes: float64(7), int64(1), object(17)
memory usage: 19.1+ MB

In [10]:
df.shape

(100000, 25)

In [11]:
df.columns

Index(['Order_ID', 'Order_Date', 'Delivery_Date', 'Customer_Name',
       'Customer_Email', 'Customer_Phone', 'Customer_City', 'Customer_State',
       'Customer_Pincode', 'Region', 'Category', 'Sub_Category',
       'Product_Name', 'Product_SKU', 'Quantity', 'Unit_Price_INR',
       'Discount_Percent', 'Tax_Percent', 'Gross_Amount_INR', 'Net_Amount_INR',
       'Payment_Method', 'Payment_Status', 'Shipping_Method',
       'Customer_Rating', 'Return_Status'],
      dtype='object')

In [12]:
df.describe()

,Customer_Phone,Customer_Pincode,Quantity,Discount_Percent,Tax_Percent,Gross_Amount_INR,Net_Amount_INR,Customer_Rating
count,9.899600e+04,99035.000000,100000.000000,98926.000000,98027.000000,1.000000e+05,9.704500e+04,98006.000000
mean,8.993317e+11,527900.944262,6.189760,31.663346,12.631714,4.794456e+05,3.718308e+05,3.035506
std,1.295726e+11,277762.101224,22.116066,25.363916,9.839965,1.941093e+06,1.608757e+06,1.488470
min,1.030000e+02,103.000000,-9.000000,-196.870000,0.000000,0.000000e+00,-1.824893e+07,-10.000000
25%,9.169360e+11,297091.500000,3.000000,14.720000,5.000000,1.182421e+05,8.275352e+04,2.000000
50%,9.179565e+11,532496.000000,5.000000,30.250000,12.000000,2.863406e+05,2.113656e+05,3.000000
75%,9.189782e+11,766195.000000,7.000000,45.790000,18.000000,5.661988e+05,4.317752e+05,4.000000
max,9.200000e+11,999993.000000,499.000000,199.850000,28.000000,7.307701e+07,9.353857e+07,10.000000

In [14]:
df.describe(include = 'O')

,Order_ID,Order_Date,Delivery_Date,Customer_Name,Customer_Email,Customer_City,Customer_State,Region,Category,Sub_Category,Product_Name,Product_SKU,Unit_Price_INR,Payment_Method,Payment_Status,Shipping_Method,Return_Status
count,99500,98990,97031,99014,99018,93215,88108,81744,93659,98995,97992,100000,99500,86780,82047,77579,90628
unique,96590,4124,4167,1200,96745,28,22,9,15,50,39860,60513,99205,13,9,7,10
top,ORD00058265,04-10-2020,06-12-2022,Priya Joshi,rahul.sharma216@hotmail.com,Kanpur,WB,South,Electronics,Action Figures,Beauty - Makeup Model 378,SKU39569,121788.45,cash,Pending,Express,FALSE
freq,4,81,83,271,3,3432,4071,9236,6432,2064,10,9,2,6781,9284,11171,9207

In [15]:
df.describe(include = 'all')

,Order_ID,Order_Date,Delivery_Date,Customer_Name,Customer_Email,Customer_Phone,Customer_City,Customer_State,Customer_Pincode,Region,...,Unit_Price_INR,Discount_Percent,Tax_Percent,Gross_Amount_INR,Net_Amount_INR,Payment_Method,Payment_Status,Shipping_Method,Customer_Rating,Return_Status
count,99500,98990,97031,99014,99018,9.899600e+04,93215,88108,99035.000000,81744,...,99500,98926.000000,98027.000000,1.000000e+05,9.704500e+04,86780,82047,77579,98006.000000,90628
unique,96590,4124,4167,1200,96745,NaN,28,22,NaN,9,...,99205,NaN,NaN,NaN,NaN,13,9,7,NaN,10
top,ORD00058265,04-10-2020,06-12-2022,Priya Joshi,rahul.sharma216@hotmail.com,NaN,Kanpur,WB,NaN,South,...,121788.45,NaN,NaN,NaN,NaN,cash,Pending,Express,NaN,FALSE
freq,4,81,83,271,3,NaN,3432,4071,NaN,9236,...,2,NaN,NaN,NaN,NaN,6781,9284,11171,NaN,9207
mean,NaN,NaN,NaN,NaN,NaN,8.993317e+11,NaN,NaN,527900.944262,NaN,...,NaN,31.663346,12.631714,4.794456e+05,3.718308e+05,NaN,NaN,NaN,3.035506,NaN
std,NaN,NaN,NaN,NaN,NaN,1.295726e+11,NaN,NaN,277762.101224,NaN,...,NaN,25.363916,9.839965,1.941093e+06,1.608757e+06,NaN,NaN,NaN,1.488470,NaN
min,NaN,NaN,NaN,NaN,NaN,1.030000e+02,NaN,NaN,103.000000,NaN,...,NaN,-196.870000,0.000000,0.000000e+00,-1.824893e+07,NaN,NaN,NaN,-10.000000,NaN
25%,NaN,NaN,NaN,NaN,NaN,9.169360e+11,NaN,NaN,297091.500000,NaN,...,NaN,14.720000,5.000000,1.182421e+05,8.275352e+04,NaN,NaN,NaN,2.000000,NaN
50%,NaN,NaN,NaN,NaN,NaN,9.179565e+11,NaN,NaN,532496.000000,NaN,...,NaN,30.250000,12.000000,2.863406e+05,2.113656e+05,NaN,NaN,NaN,3.000000,NaN
75%,NaN,NaN,NaN,NaN,NaN,9.189782e+11,NaN,NaN,766195.000000,NaN,...,NaN,45.790000,18.000000,5.661988e+05,4.317752e+05,NaN,NaN,NaN,4.000000,NaN
max,NaN,NaN,NaN,NaN,NaN,9.200000e+11,NaN,NaN,999993.000000,NaN,...,NaN,199.850000,28.000000,7.307701e+07,9.353857e+07,NaN,NaN,NaN,10.000000,NaN

In [17]:
df.dtypes

Order_ID             object
Order_Date           object
Delivery_Date        object
Customer_Name        object
Customer_Email       object
Customer_Phone      float64
Customer_City        object
Customer_State       object
Customer_Pincode    float64
Region               object
Category             object
Sub_Category         object
Product_Name         object
Product_SKU          object
Quantity              int64
Unit_Price_INR       object
Discount_Percent    float64
Tax_Percent         float64
Gross_Amount_INR    float64
Net_Amount_INR      float64
Payment_Method       object
Payment_Status       object
Shipping_Method      object
Customer_Rating     float64
Return_Status        object
dtype: object