In [6]:
import numpy as np
import pandas as pd
import matplotlib as plt
import seaborn as sns

## Data Collection

In [11]:
df = pd.read_excel("amazon_ecommerce_messy.xlsx")

In [12]:
df

,Order_ID,Customer_ID,Product_ID,Product_Name,Category,Sub_Category,Price,Quantity,Discount_Percent,Order_Date,...,Reviews_Count,Return_Status,Customer_Age,Customer_Gender,City,State,Pincode,Customer_Since,Total_Orders,Loyalty_Member
0,ORD-0033913,CUST-18283,PROD-118762,Beauty,Books,Car Accessories,2397.287801,5,15,2025-10-09 18:07:25.816000,...,226,Pending,43,NaN,Ahmedabad,NaN,222027,2025-12-23 18:07:28.598000,51,0
1,ORD-0012022-DUP,CUST-26624,NaN,Automotive,NaN,UNKNOWN,3109.077693,4,5,2026-01-10 18:07:25.780000,...,108,MAYBE,23,Male,CITY,Delhi,XXXX,2025-05-29 18:07:28.563000,21,MAYBE
2,ORD-0073409,CUST-13485,PROD-890878,Fashion,Beauty,Car Accessories,2943.496217,5,10,2026-03-29 18:07:25.882000,...,1,NaN,48,NaN,Pune,NaN,808667,2022-12-26 18:07:28.658000,12,1
3,NaN,CUST-48461,PROD-446550,Home & Kitchen,Toys,NaN,2903.444083,5,25,2025-07-22 18:07:25.910000,...,189,MAYBE,68,NaN,Kolkata,Tamil Nadu,811679,2026-03-09 18:07:28.685000,88,NaN
4,ORD-0038507,CUST-37022,PROD-622689,Automotive,Electronics,Shoes,3766.788567,6,150,2025-11-21 18:07:25.823000,...,13,NaN,49,M,Chennai,UNKNOWN,875923,2023-07-13 18:07:28.605000,48,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106995,ORD-0032500,CUST-27144,PROD-613824,Books,Auto,Smartphones,3913.50899,1,-10,Invalid Date,...,263,NaN,22,Male,CITY,UNKNOWN,218743,2025-03-18 18:07:28.596000,8,Yes
106996,ORD-0028983,CUST-18202,PROD-922459,Home & Kitchen,NaN,Bedding,1050.273505,2,0,2026-03-31 18:07:25.808000,...,169,No,65,F,Mumbai,West Bengal,320617,2024-05-14 18:07:28.590000,10,Yes
106997,ORD-0079887,CUST-07550,PROD-535720,Automotive,Home,Car Accessories,4953.305439,4,-10,2025-06-16 18:07:25.892000,...,32,Yes,21,NaN,NaN,Karnataka,694855,2025-03-13 18:07:28.668000,95,1
106998,ORD-0064198,CUST-48620,PROD-966889,Home & Kitchen,NaN,UNKNOWN,4870.634878,9,25,2026-01-08 18:07:25.866000,...,231,NaN,37,Male,Pune,Maharashtra,674108,2025-02-27 18:07:28.644000,18,0
106999,ORD-0093995,CUST-22752,PROD-477626,Toys,Sports,Car Accessories,NaN,6,40,2025-06-22 18:07:25.915000,...,289,Yes,39,Female,Chennai,NaN,937460,NaN,85,0

## Data Understanding

In [13]:
df.head()

,Order_ID,Customer_ID,Product_ID,Product_Name,Category,Sub_Category,Price,Quantity,Discount_Percent,Order_Date,...,Reviews_Count,Return_Status,Customer_Age,Customer_Gender,City,State,Pincode,Customer_Since,Total_Orders,Loyalty_Member
0,ORD-0033913,CUST-18283,PROD-118762,Beauty,Books,Car Accessories,2397.287801,5,15,2025-10-09 18:07:25.816000,...,226,Pending,43,NaN,Ahmedabad,NaN,222027,2025-12-23 18:07:28.598000,51,0
1,ORD-0012022-DUP,CUST-26624,NaN,Automotive,NaN,UNKNOWN,3109.077693,4,5,2026-01-10 18:07:25.780000,...,108,MAYBE,23,Male,CITY,Delhi,XXXX,2025-05-29 18:07:28.563000,21,MAYBE
2,ORD-0073409,CUST-13485,PROD-890878,Fashion,Beauty,Car Accessories,2943.496217,5,10,2026-03-29 18:07:25.882000,...,1,NaN,48,NaN,Pune,NaN,808667,2022-12-26 18:07:28.658000,12,1
3,NaN,CUST-48461,PROD-446550,Home & Kitchen,Toys,NaN,2903.444083,5,25,2025-07-22 18:07:25.910000,...,189,MAYBE,68,NaN,Kolkata,Tamil Nadu,811679,2026-03-09 18:07:28.685000,88,NaN
4,ORD-0038507,CUST-37022,PROD-622689,Automotive,Electronics,Shoes,3766.788567,6,150,2025-11-21 18:07:25.823000,...,13,NaN,49,M,Chennai,UNKNOWN,875923,2023-07-13 18:07:28.605000,48,Yes

In [14]:
df.tail()

,Order_ID,Customer_ID,Product_ID,Product_Name,Category,Sub_Category,Price,Quantity,Discount_Percent,Order_Date,...,Reviews_Count,Return_Status,Customer_Age,Customer_Gender,City,State,Pincode,Customer_Since,Total_Orders,Loyalty_Member
106995,ORD-0032500,CUST-27144,PROD-613824,Books,Auto,Smartphones,3913.50899,1,-10,Invalid Date,...,263,NaN,22,Male,CITY,UNKNOWN,218743,2025-03-18 18:07:28.596000,8,Yes
106996,ORD-0028983,CUST-18202,PROD-922459,Home & Kitchen,NaN,Bedding,1050.273505,2,0,2026-03-31 18:07:25.808000,...,169,No,65,F,Mumbai,West Bengal,320617,2024-05-14 18:07:28.590000,10,Yes
106997,ORD-0079887,CUST-07550,PROD-535720,Automotive,Home,Car Accessories,4953.305439,4,-10,2025-06-16 18:07:25.892000,...,32,Yes,21,NaN,NaN,Karnataka,694855,2025-03-13 18:07:28.668000,95,1
106998,ORD-0064198,CUST-48620,PROD-966889,Home & Kitchen,NaN,UNKNOWN,4870.634878,9,25,2026-01-08 18:07:25.866000,...,231,NaN,37,Male,Pune,Maharashtra,674108,2025-02-27 18:07:28.644000,18,0
106999,ORD-0093995,CUST-22752,PROD-477626,Toys,Sports,Car Accessories,NaN,6,40,2025-06-22 18:07:25.915000,...,289,Yes,39,Female,Chennai,NaN,937460,NaN,85,0